PROXMOX_VE_ENDPOINT: ENC[AES256_GCM,data:8QaB5eMR6AKT+aTRA34WwFLVHs3ygaEX,iv:jzwNef3cG4c/WRjYxrkZLiDKnZg+sGgUE790XowSphs=,tag:spBiGhzwzDZv5/ncFZGAYA==,type:str]
PROXMOX_VE_API_TOKEN: ENC[AES256_GCM,data:W4oN8/qlijO0xPlOfRwRG5Arazf1tGpwGh7YCkA/GVpNkD+tlpiTjw3pi4T7vG6g9ik=,iv:QXSnSYSiBHgABy4hfkrFsAOfstev9dReI+N1gs1vU0k=,tag:DMhb53GlUe+iiqe1tLG6cQ==,type:str]
PROXMOX_VE_INSECURE: ENC[AES256_GCM,data:EfH9fg==,iv:MzPk4lpbLeiUfHVPT2cEMEhO59joTqXIRXiBE9Pum2U=,tag:+RY6RHjIPWmKwA5X9EPY1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WTMxZHQ3MGJjK1IrTmVm
            RG5nR3VqeFF3emkwM1I4bXJhSjEycHhPa2dVCjdQcGU2UWl2dVprU3FoMjJFS1Zy
            QktzMEMzZFJxc0JhajNsN3lZb2pMRUkKLS0tIHJ4WEhvV3dxcDF1YXJVV21PTDBR
            eEVSSldaNk01b3RoNk9HVWtXTVlJckUK1apFMTz0/VLt3QdpbVAw+/3JUTZM9U9o
            oeA8KdP/Ogywr9izerYqwTVd4173dkephUtlao6iJxcvlJv39lRhMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xce70l2z2l5hfuu3ynek4lrwpfa0vz4yxtjh299vq2d609azqyrqdfgke2
    lastmodified: "2026-07-17T23:19:17Z"
    mac: ENC[AES256_GCM,data:5BUTgPekAS8xnTcyHc0BIvGQZ6JrqsFxk8ogOfbPA7saAWO+0CFnhW/gSibmXN2r+7J0mbLPQbZnjRp0vnZ3mCFtQiOuYXYtTtos6aSXbbq01HFwnNQNQasIOR2lsG4BxAwCTWz4hMbTCcpGRXk7NM83nH93r7MYU/ZlWyglxw4=,iv:iPyU9uxh+DTNGpG3JKkXZtKK0Ock76JmorOdkOVNuQ8=,tag:I6d1vTUvV5Svsxpu7rhyKg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
