PROXMOX_VE_ENDPOINT: ENC[AES256_GCM,data:J650qwM7dK0znaUWQeY/nH+EmHKHojhbNQ==,iv:JBrE6tdBCM2hJnBsojq/d31Mg5SzqCAnhOpPZmKsAE0=,tag:fozibkXiAKBPd2wSnN9+Ew==,type:str]
PROXMOX_VE_API_TOKEN: ENC[AES256_GCM,data:W4oN8/qlijO0xPlOfRwRG5Arazf1tGpwGh7YCkA/GVpNkD+tlpiTjw3pi4T7vG6g9ik=,iv:QXSnSYSiBHgABy4hfkrFsAOfstev9dReI+N1gs1vU0k=,tag:DMhb53GlUe+iiqe1tLG6cQ==,type:str]
PROXMOX_VE_INSECURE: ENC[AES256_GCM,data:EfH9fg==,iv:MzPk4lpbLeiUfHVPT2cEMEhO59joTqXIRXiBE9Pum2U=,tag:+RY6RHjIPWmKwA5X9EPY1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WTMxZHQ3MGJjK1IrTmVm
            RG5nR3VqeFF3emkwM1I4bXJhSjEycHhPa2dVCjdQcGU2UWl2dVprU3FoMjJFS1Zy
            QktzMEMzZFJxc0JhajNsN3lZb2pMRUkKLS0tIHJ4WEhvV3dxcDF1YXJVV21PTDBR
            eEVSSldaNk01b3RoNk9HVWtXTVlJckUK1apFMTz0/VLt3QdpbVAw+/3JUTZM9U9o
            oeA8KdP/Ogywr9izerYqwTVd4173dkephUtlao6iJxcvlJv39lRhMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xce70l2z2l5hfuu3ynek4lrwpfa0vz4yxtjh299vq2d609azqyrqdfgke2
    lastmodified: "2026-06-05T13:03:10Z"
    mac: ENC[AES256_GCM,data:8ZK/LrruZMj1dXnK5qh96NFmnh3GoZ58KOxSnY9IDdAall+AeG7b8sN89TRg0SJvw4odHuGImYkfiRTkX5qUbBKEmwG3R8XcErjaIVPrF24reT3lO7uxU2XANwtglo4Vx4zqUT537XcjGWj0O3t23ofKnF83xb5wmcAV1v5Hgtg=,iv:ETybp7FQCgljnJj5hzHOjUcwKLm+2d1O+Hf1erZgHW0=,tag:4W8oM6pqhLg4gOpdQNOeBw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
