ROS_HOSTURL: ENC[AES256_GCM,data:n1vpWx8KfSkIN1yZ75v9fvw=,iv:ol0YRNtxuQ1by+DZ5YVD6IqN0yqUzVb2w4YLYaoGfPA=,tag:7nWbaFHVKWnU1T0g7iq/7Q==,type:str]
ROS_USERNAME: ENC[AES256_GCM,data:4+thSw==,iv:0AbbA502vitO9MSbcj7os/TI++e8fM4Q9ALIMLfbMCI=,tag:me8FpA3LjlP8toHcOw2XjA==,type:str]
ROS_PASSWORD: ENC[AES256_GCM,data:1y/lzLXIz1+JhP6nbOZ3CM0okL5nQctoMukG7oQeuMI=,iv:3Ok33jImjH5QZRsAmXdzqkr8wkX/vEiOWH0viN5SKJQ=,tag:nRZ6grkqef8BWymCadtf1g==,type:str]
ROS_INSECURE: ENC[AES256_GCM,data:aud/zw==,iv:pqU2FJj5418PM/Mp3P0I6VNk137HzsX2uoEc8xJwXFw=,tag:0qr/GU2M20WFTA43J3yIXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBranRkanhzb3RmNUtNUm1K
            U1dBWEZoOVJ5ZjVkQTl6OU8veEFmOElSR2tJClBWajAzN2FwZkxrTVlRVzQ5RER2
            VUpCbjJHSU5BZk1uZ1ZIeU5PQ2J5V2MKLS0tIFNxNW9VTTcvYXNsSzR3aUdVeVRE
            WG1uZE9QT3dPeHoweWRSNGhkalVjdEkK0hBFk2XMuogUQFnBJK5SPlb4J3cKJbb1
            HnjIfZYEgh0ju8nX6U9RtdYcXcGiNkAJz7ktUnNkuWaMHad9u09l/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xce70l2z2l5hfuu3ynek4lrwpfa0vz4yxtjh299vq2d609azqyrqdfgke2
    lastmodified: "2026-06-03T00:40:47Z"
    mac: ENC[AES256_GCM,data:O0UM3yb/TBk+gZ0p/UrfT/lJ7p8fSA13Rkosk2XuFbmHD+i8alv1Sx5j9PTu105RuwOY9lOZxOJ8x7n8xnfJDuLW6PULAqN1QmbW3SJ/iJ2FdwapNXdJkJG4abhj4Kmv722vVNrSul2REmedZ26unIBLuCxX4uejef0Fmi6lv4E=,iv:MftfYiKQP23tEsaINEsKebO3QQXdI6peLh9BCQICZ9U=,tag:5K66XReusGB34ZhPlmeT6g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
